---
title: "baySeq_Neo4j_CypherScripts"
author: "Mallory Lai"
date: "August 23, 2016"
output: html_document
---
**The purpose of this file is to record Cypher scripts used by the
author, Mallory Lai, during the course of importing
Brassica RNA-Seq data into Neo4j.**  

LazyWebCypher was used to run multi-statement scripts. 
http://www.lyonwj.com/LazyWebCypher/

# Importation:

    CREATE CONSTRAINT ON (g:Gene) ASSERT g.id IS UNIQUE;  
    
    USING PERIODIC COMMIT 100  
    LOAD CSV WITH HEADERS FROM   
    'file:///full_Neo4j.csv' AS line  
    
    MERGE  (g:Gene {id: line.Gene})  
    MERGE (c:Count {count: TOINT(line.Count)})  
    MERGE (tm:Treatment {trmt: (line.Treatment)})  
    MERGE (t:Tissue {tissue: (line.Tissue)})  
    CREATE (g)-[:TRANSCRIBES_TO {replicate: TOINT(line.Replicate)}]->(c)  
    CREATE (tm)-[:TREATMENT]->(g)  

This doesn't place constraint on relationship. Redundant relationships exist.   
    
The following code doesn't work: 

    CREATE CONSTRAINT ON (g:Gene) ASSERT g.id IS UNIQUE;    
    CREATE CONSTRAINT ON (c:Count) ASSERT c.count IS UNIQUE;    
    CREATE CONSTRAINT ON (tm:Treatment) ASSERT tm.trmt IS UNIQUE;    
    CREATE CONSTRAINT ON (t:Tissue) ASSERT t.type IS UNIQUE;    

    USING PERIODIC COMMIT 100    
    LOAD CSV WITH HEADERS FROM     
    'file:///full_Neo4j.csv' AS line    

    CREATE  (g:Gene {id: line.Gene})    
    CREATE (c:Count {count: TOINT(line.Count)})    
    CREATE (tm:Treatment {trmt: (line.Treatment)})    
    CREATE (t:Tissue {type: (line.Tissue)})    

    
Interestingly, this returns the wrong number of rows: 

    CREATE CONSTRAINT ON (g:Gene) ASSERT g.id IS UNIQUE;  

    USING PERIODIC COMMIT 100  
    LOAD CSV WITH HEADERS FROM   
    'file:///full_Neo4j.csv' AS line  

    CREATE  (g:Gene {id: line.Gene})  

This returns 26,998 genes instead of 27,023. That's short 25 genes. 

But... This returns the correct number of rows: 

    USING PERIODIC COMMIT 100  
    LOAD CSV WITH HEADERS FROM   
    'file:///full_Neo4j.csv' AS line  

    MERGE  (g:Gene {id: line.Gene})  

This returns 5,480 unique counts instead of 8,286.   
   
    USING PERIODIC COMMIT 100  
    LOAD CSV WITH HEADERS FROM   
    'file:///full_Neo4j.csv' AS line  

    MERGE (c:Count {count: TOINT(line.Count)})  

Perhaps TOINT is the problem...
Yes! Changing TOINT to TOFLOAT corrects this.

    USING PERIODIC COMMIT 100  
    LOAD CSV WITH HEADERS FROM   
    'file:///full_Neo4j.csv' AS line  

    MERGE (c:Count {count: TOFLOAT(line.Count)})  

Ok. All together now: 

    USING PERIODIC COMMIT 100  
    LOAD CSV WITH HEADERS FROM   
    'file:///IMB211_DP_NDP_RNAseq_Neo4j.csv' AS line  

    MERGE (c:Count {count: TOFLOAT(line.Count)}) 
    MERGE  (g:Gene {id: line.Gene})
    MERGE (tm:Treatment {trmt: (line.Treatment)})  
    MERGE (t:Tissue {tissue: (line.Tissue)})      
    
Looks good. Now let's try to create UNIQUE relationships.     
    
    USING PERIODIC COMMIT 100  
    LOAD CSV WITH HEADERS FROM   
    'file:///IMB211_DP_NDP_RNAseq_Neo4j.csv' AS line  

    MERGE (c:Count {count: TOFLOAT(line.Count)})
    MERGE (t:Tissue {tissue: (line.Tissue)}) 
    MERGE (t)-[:TREATMENT {replicate: TOINT(line.Replicate)}]->(c)

This is interesting. The relationship is wrong (should say Tissue) but it's
much better than previous attempts. Snapshot saved on Desktop as 
merge_relationship.

Looking good!

    USING PERIODIC COMMIT 100  
    LOAD CSV WITH HEADERS FROM   
    'file:///IMB211_DP_NDP_RNAseq_Neo4j.csv' AS line  

    MERGE (c:Count {count: TOFLOAT(line.Count)}) 
    MERGE (g:Gene {id: line.Gene})
    MERGE (tm:Treatment {trmt: (line.Treatment)})  
    MERGE (t:Tissue {tissue: (line.Tissue)}) 
    MERGE (tm)-[:TREATMENT]->(g)
    MERGE (g)-[:TRANSCRIBES_TO {replicate: TOINT(line.Replicate)}]->(c)
    MERGE (t)-[:TISSUE_TYPE]->(c)

Now let's try some queries. 

Here's a very simple query: Find RNA-seq counts equal to 7.

    MATCH (n:Count)
    WHERE n.count = 7
    RETURN n
    
This will show the genes that transcribe to a count of 47.

    MATCH (n:Count)<-[r]-(m)
    WHERE n.count = 47
    RETURN distinct n,r,m
    
Concerned that my query doesn't yeild tissue type. However, this does: 

    MATCH (n:Count)<-[r:TISSUE_TYPE]-(m)
    WHERE n.count = 47
    RETURN distinct n,r,m
    
Checking a unique value: 129,794.5

    MATCH (k)-->(n:Count)<-[r:TISSUE_TYPE]-(m)
    WHERE n.count = 129794.5
    RETURN distinct n,r,m,k
    
Looks good! Let's check Treatment to make sure it's NDP.

    MATCH (k)-[r:TREATMENT]->(j)-[q:TRANSCRIBES_TO]->(n:Count)
    WHERE n.count = 129794.5
    RETURN distinct n,r,k,j,q

Uh-oh. No way to tell whether the Count came from the DP or NDP Treatment. 
Let's try to create the Treatment relationship from Treatment to Count instead
of Gene. 

    USING PERIODIC COMMIT 100  
    LOAD CSV WITH HEADERS FROM   
    'file:///IMB211_DP_NDP_RNAseq_Neo4j.csv' AS line  

    MERGE (c:Count {count: TOFLOAT(line.Count)}) 
    MERGE (g:Gene {id: line.Gene})
    MERGE (tm:Treatment {trmt: (line.Treatment)})  
    MERGE (t:Tissue {tissue: (line.Tissue)}) 
    MERGE (tm)-[:TREATMENT]->(c)
    MERGE (g)-[:TRANSCRIBES_TO {replicate: TOINT(line.Replicate)}]->(c)
    MERGE (t)-[:TISSUE_TYPE]->(c)

Let's check that unique value again. 

    MATCH (n:Count)<-[r]-(m)
    WHERE n.count = 129794.5
    RETURN distinct n,r,m
  
Great! Now let's check a value that's not unique but doesn't have too
many multiples. Let's do: 3048.5.
  
    MATCH (n:Count)<-[r]-(m)
    WHERE n.count = 3048.5
    RETURN distinct n,r,m

There are two treatments, three genes, and two tissue types. It's not possible
to tell which combinations led to the count of 3048.5.

Perhaps indices are needed... 
  
  
  
  
  
TO DO (M.Lai):
Let's try to add the R500 data. 
Merging IMB211 and R500 data may be easier than matching and merging data sets.

```{r}

#IMB211 <- read.csv(file = "IMB211_DP_NDP_RNAseq_Neo4j.csv")
#R500 <- read.csv(file = "R500_DP_NDP_RNAseq_Neo4j.csv")
    
```    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    